### ISSUE TITLE
Next.js should not be prohibited

### ISSUE THREAD

**Issue by LeTanque** [Lambda-School-Labs/labs-engineering-standards#50] opened 2020-02-03 21:06 UTC
This issue is a mostly-repost from my comment in #43 

**_With regards to Next.js in Labs:_**

CRA is React 
AND 
Next.js is React

The differences are, more or less, webpack configuration, how the developer thinks about their app when developing, and the react-scripts dependency. But at its core Next.js is React.

I completely agree with the reasoning on the PR that we are a "react shop". By that reasoning, there is little reason to prohibit Next.js in labs.

**_Summary_**:
I really think Next.js should be an available option for teams! If not for all, at least on a case by case business. 

For my Labs team, I led the research on Next.js and we ended up not using it for Labs. But the process of researching and thinking critically about how our problem related to our solutions helped me understand what we were building at a deeper level. That research, in my opinion, helped our team finish as one of the strongest apps in our cohort.

**Comment by berniedurfee** [comment] 2020-02-04 14:42
Closing this as a duplicate of #43. That issue will be used to decide whether to permit Next.js _and_ CRA or just CRA.

**Closed by berniedurfee** 2020-02-04 14:42 UTC
Labels: duplicate
